In [20]:
#Let's first import required Python packages.
#Importing required Python packages
import matplotlib.pylab as plt
import numpy as np
from sklearn.model_selection import ShuffleSplit, train_test_split
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier
from xgboost.sklearn import XGBClassifier  

import pandas as pd
np.random.seed(42)

In [18]:
traincsv=pd.read_csv('train.csv', index_col='Id')
testcsv=pd.read_csv('test.csv', index_col='Id')

print traincsv.shape, testcsv.shape
print type(traincsv), type(testcsv)

(15120, 55) (565892, 54)
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>


In [3]:
#80/20 Split
X_train, X_test, y_train, y_test = train_test_split(traincsv.iloc[:,:-1].values, traincsv.iloc[:,-1:].values.ravel(), 
                                                    test_size=0.2)

print X_train.shape, X_test.shape, y_train.shape, y_test.shape

print type(X_train), type(X_test), type(y_train), type(y_test)

(12096, 54) (3024, 54) (12096,) (3024,)
<type 'numpy.ndarray'> <type 'numpy.ndarray'> <type 'numpy.ndarray'> <type 'numpy.ndarray'>


In [4]:
RFC=RandomForestClassifier(max_depth=14, n_estimators=1000)
RFC.fit(X_train, y_train)

ETC= ExtraTreesClassifier(max_depth=14, n_estimators=1000)
ETC.fit(X_train, y_train)

GBC= GradientBoostingClassifier(max_depth=14, n_estimators=1000)
GBC.fit(X_train, y_train)

XGB= XGBClassifier(max_depth=14, n_estimators=1000)
XGB.fit(X_train, y_train)

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=14,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='multi:softprob', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

In [5]:
estimators = [RFC, ETC, GBC, XGB]

X_blend_train   =  []
X_blend_test    =  []
X_blend_testcsv =  []

print type(X_blend_train), type(X_blend_test), type(X_blend_testcsv)

for i, est in enumerate(estimators):
    print i , est
    X_blend_train.append(est.predict(X_train))
    X_blend_test.append(est.predict(X_test))
    X_blend_testcsv.append(est.predict(testcsv.values))
    print len(X_blend_train), len(X_blend_test), len(X_blend_testcsv)
    print X_blend_train
    print X_blend_test
    print X_blend_testcsv

<type 'list'> <type 'list'> <type 'list'>
0 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=14, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=1, oob_score=False,
            random_state=None, verbose=0, warm_start=False)
1 1 1
[array([3, 5, 2, ..., 2, 5, 7])]
[array([6, 6, 1, ..., 5, 4, 4])]
[array([2, 2, 2, ..., 3, 3, 3])]
1 ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=14, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=1000, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)
2 2 2
[array([3, 5, 2, ..., 2, 5, 7]), array([3, 5, 2, ..., 2, 5, 7])]
[array([6, 6, 1, .

In [22]:
print X_blend_train
print X_blend_test
print X_blend_testcsv

print len(X_blend_train), len(X_blend_test), len(X_blend_testcsv)
print X_blend_train.shape, X_blend_test.shape, X_blend_testcsv.shape
print type(X_blend_train), type(X_blend_test), type(X_blend_testcsv)

X_blend_train = np.array(X_blend_train).T
X_blend_test = np.array(X_blend_test).T
X_blend_testcsv = np.array(X_blend_testcsv).T

print X_blend_train
print X_blend_test
print X_blend_testcsv

print len(X_blend_train), len(X_blend_test), len(X_blend_testcsv)
print X_blend_train.shape, X_blend_test.shape, X_blend_testcsv.shape
print type(X_blend_train), type(X_blend_test), type(X_blend_testcsv)

[[3 5 2 ..., 2 5 7]
 [3 5 2 ..., 2 5 7]
 [3 5 2 ..., 2 5 7]
 [3 5 2 ..., 2 5 7]]
[[6 6 1 ..., 5 4 4]
 [4 6 1 ..., 5 4 4]
 [6 6 1 ..., 5 4 4]
 [6 3 1 ..., 5 4 4]]
[[2 2 2 ..., 3 3 3]
 [2 2 2 ..., 3 3 3]
 [5 5 1 ..., 3 3 3]
 [5 5 1 ..., 3 3 3]]
4 4 4
(4, 12096) (4, 3024) (4, 565892)
<type 'numpy.ndarray'> <type 'numpy.ndarray'> <type 'numpy.ndarray'>
[[3 3 3 3]
 [5 5 5 5]
 [2 2 2 2]
 ..., 
 [2 2 2 2]
 [5 5 5 5]
 [7 7 7 7]]
[[6 4 6 6]
 [6 6 6 3]
 [1 1 1 1]
 ..., 
 [5 5 5 5]
 [4 4 4 4]
 [4 4 4 4]]
[[2 2 5 5]
 [2 2 5 5]
 [2 2 1 1]
 ..., 
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
12096 3024 565892
(12096, 4) (3024, 4) (565892, 4)
<type 'numpy.ndarray'> <type 'numpy.ndarray'> <type 'numpy.ndarray'>


In [19]:
XGB2= XGBClassifier(max_depth=14, n_estimators=1000).fit(X_blend_train, y_train) 
y_pred=XGB2.predict(X_blend_test)

#Make a copy of the test.csv 
temp=testcsv.copy()

#Run Predictions on test.csv 
temp['Cover_Type']=XGB2.predict(X_blend_testcsv) 

#Create Submissions csv file 
temp=temp['Cover_Type'] 
temp.to_csv('SampleSubmission17', header=True) 
print 'complete'

complete


In [8]:
# Public Score : 0.74605